email_categories = {
    "Task Assignments": "Explicitly assigning specific tasks to individuals.",
    "Meeting Follow-ups": "Action items identified during or after meetings.",
    "Project Milestones": "Tasks or goals that need to be achieved in a project.",
    "Deadlines": "Clearly stated deadlines for specific actions.",
    "Collaboration Requests": "Invitations to contribute or collaborate on a task.",
    "Feedback Requests": "Seeking feedback or input on particular matters.",
    "Decision Points": "Identifying actions necessary for making decisions.",
    "Training Requirements": "Tasks related to learning or skill development.",
    "Policy Implementation": "Action items tied to the implementation of new policies.",
    "Client Requests": "Tasks prompted by client needs or expectations.",
    "Project Updates": "Emails providing updates on ongoing projects.",
    "Meeting Requests": "Invitations or requests to schedule meetings.",
    "Task Assignments (Emails)": "Emails assigning tasks or responsibilities.",
    "Deadline Reminders": "Notifications about upcoming deadlines.",
    "Team Communication": "General communication within a team or department.",
    "Policy Updates": "Emails informing about changes in company policies.",
    "Training Opportunities": "Notifications about training programs or opportunities.",
    "Performance Reviews": "Correspondence related to employee performance evaluations.",
    "HR Announcements": "Information from Human Resources about policies or events.",
    "Client Communication": "Emails related to client interactions or projects.",
    "Utility Bills": "Electricity, water, gas bills, etc.",
    "Subscription Invoices": "Invoices for services or subscriptions.",
    "Loan Payments": "Notifications for loan repayments.",
    "Credit Card Statements": "Statements indicating credit card charges.",
    "Bills/Invoices": "Requests for payment or notifications of amounts due.",
    "Meeting Invitations": "Emails inviting recipients to attend meetings.",
    "Job Application Responses": "Replies to job applications or interview invitations.",
    "Travel Confirmations": "Emails confirming flight, hotel, or other travel details.",
    "Subscription Renewals": "Notifications for renewing subscriptions or memberships.",
    "Feedback Requests (Emails)": "Emails seeking feedback on products or services.",
    "Product Updates": "Information about updates or changes to a product or service.",
    "Security Alerts": "Notifications about account security or login activities.",
    "Event Reminders": "Reminders for upcoming events or appointments.",
    "Emergency Notifications": "Alerts about urgent matters or unexpected events.",
    "Personal Correspondence": "Emails exchanged for personal communication.",
    "Work-related Messages": "Business emails, project updates, or work-related discussions.",
    "Newsletters": "Regular updates or information from subscriptions.",
    "Promotional Emails": "Marketing messages, sales, or promotional offers.",
    "Social Notifications": "Email alerts from social media platforms.",
    "Transactional Emails": "Confirmations, receipts, or order updates.",
    "Invitations": "Emails inviting recipients to events or gatherings.",
    "Spam/Junk Emails": "Unwanted or unsolicited messages.",
    "Educational Content": "Emails sharing educational resources or content updates.",
    "Appointment Confirmations": "Confirmations and reminders for scheduled medical appointments.",
    "Prescription Refills": "Notifications for prescription renewals or refill reminders.",
    "Test Results": "Emails communicating the results of medical tests or examinations.",
    "Billing Statements": "Invoices or statements related to medical services received.",
    "Health Insurance Updates": "Communication regarding changes in health insurance coverage.",
    "Health and Wellness Tips": "Information and advice related to maintaining good health.",
    "Vaccination Reminders": "Reminders for upcoming vaccinations or immunizations.",
    "Appointment Scheduling": "Emails facilitating the scheduling of medical appointments.",
    "Health Screenings": "Notifications for routine health screenings or check-ups.",
    "Telemedicine Appointments": "Information and instructions for virtual medical appointments."
}

nonAccessibleLabels = []
